### ISSUE TITLE
cuTensor - Python test Failed

### ISSUE THREAD

**Issue by kuangllbnu** [NVIDIA/CUDALibrarySamples#48]
I test in container "nvcr.io/nvidia/pytorch:21.04-py3".

```
$ python cutensor/torch/einsum_test.py
..........FF.
======================================================================
FAIL: test_einsum_general_equivalent_results_1_test_1 (__main__.EinsumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "cutensor/torch/einsum_test.py", line 221, in test_einsum_general_equivalent_results
    torch.testing.assert_allclose(cutensor_rslt, torch_rslt, rtol=5e-3, atol=5e-3)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/__init__.py", line 250, in assert_allclose
    raise AssertionError(msg)
AssertionError: With rtol=0.005 and atol=0.005, found 1 element(s) (out of 400) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.012973159551620483 (-0.4519635736942291 vs. -0.4649367332458496), which occurred at index (15, 3).

======================================================================
FAIL: test_einsum_general_equivalent_results_2_test_2 (__main__.EinsumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "cutensor/torch/einsum_test.py", line 221, in test_einsum_general_equivalent_results
    torch.testing.assert_allclose(cutensor_rslt, torch_rslt, rtol=5e-3, atol=5e-3)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/__init__.py", line 250, in assert_allclose
    raise AssertionError(msg)
AssertionError: With rtol=0.005 and atol=0.005, found 4 element(s) (out of 400) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.024122774600982666 (-0.7208095192909241 vs. -0.6966867446899414), which occurred at index (21, 6).

----------------------------------------------------------------------
Ran 13 tests in 2.600s

FAILED (failures=2)

```
Sometimes, test0 failed.

**Comment by kuangllbnu** [comment]
After I set `export NVIDIA_TF32_OVERRIDE=0`, all the test pass. The failures come from the using of TF32 for the FP32.
